/* Copyright(C) 2007 National Institute of Informatics, All rights reserved.*/
CREATE USER SA PASSWORD "" ADMIN

DROP TABLE PAYMENT IF EXISTS;
DROP TABLE AVAILABLEQTY IF EXISTS;
DROP TABLE RESERVATION IF EXISTS;
DROP TABLE ROOM IF EXISTS;
CREATE TABLE PAYMENT(ROOMNUMBER VARCHAR(50) NOT NULL,STAYINGDATE VARCHAR(20) NOT NULL,ROOMTYPE VARCHAR(50) NOT NULL,AMOUNT INTEGER,STATUS VARCHAR(10),CONSTRAINT ROOMNUMBER_STAYINGDATE PRIMARY KEY(ROOMNUMBER,STAYINGDATE));
CREATE TABLE AVAILABLEQTY(DATE VARCHAR(20) NOT NULL,ROOMTYPE VARCHAR(50) NOT NULL,QTY INTEGER,CONSTRAINT DATE_ROOMTYPE PRIMARY KEY(DATE,ROOMTYPE));
CREATE TABLE RESERVATION(RESERVATIONNUMBER VARCHAR(50) NOT NULL PRIMARY KEY,STAYINGDATE VARCHAR(20),ROOMTYPE VARCHAR(50) NOT NULL,STATUS VARCHAR(10));
CREATE TABLE ROOM(ROOMNUMBER VARCHAR(50) NOT NULL PRIMARY KEY,ROOMTYPE VARCHAR(50) NOT NULL,STAYINGDATE VARCHAR(20));

INSERT INTO ROOM VALUES('1001','1','')
INSERT INTO ROOM VALUES('1002','1','')
INSERT INTO ROOM VALUES('1003','1','')
INSERT INTO ROOM VALUES('1004','1','')
INSERT INTO ROOM VALUES('1005','1','')
INSERT INTO ROOM VALUES('2001','2','')
INSERT INTO ROOM VALUES('2002','2','')
INSERT INTO ROOM VALUES('2003','2','')
INSERT INTO ROOM VALUES('2004','2','')
INSERT INTO ROOM VALUES('2005','2','')

